stages:
- name: Publish image one
  steps:
  - publishImageConfig:
      dockerfilePath: ./one/Dockerfile
      buildContext: ./one
      tag: alpine-one:${CICD_EXECUTION_SEQUENCE}
- name: Publish image two
  steps:
  - publishImageConfig:
      dockerfilePath: ./two/Dockerfile
      buildContext: ./two
      tag: alpine-two:${CICD_EXECUTION_SEQUENCE}
      env:
         PLUGIN_STORAGE_PATH: /var/lib/docker2
    
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deploy/deployment.yaml

