stages:
- name: Publish image
  steps:
  - publishImageConfig:
      dockerfilePath: ./one/Dockerfile
      buildContext: ./one
      tag: alpine-one:${CICD_EXECUTION_SEQUENCE}
  - publishImageConfig:
      dockerfilePath: ./two/Dockerfile
      buildContext: ./two
      tag: alpine-two:${CICD_EXECUTION_SEQUENCE}
    
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deploy/deployment.yaml

